version: '3.1'
 
services:
  db: 
     image: mysql:5.7
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: tcdb
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbuserpassword
     volumes:
       - dbdatatc:/var/lib/mysql
     restart: always
  teamcity:
    depends_on:
      - db
    image: jetbrains/teamcity-server:latest
    volumes:
      - teamcity-server-datadir:/data/teamcity-server/datadir
      - teamcity-server-logs:/opt/teamcity/logs
    ports:
      - 8111:8111
  teamcity-agent:
    image: jetbrains/teamcity-agent:latest
    environment:
      SERVER_URL: http://teamcity:8111
    volumes:
      - teamcity-agent-conf:/data/teamcity_agent/conf
      - /var/run/docker.sock:/var/run/docker.sock
 
volumes:
  teamcity-server-datadir:
  teamcity-server-logs:
  teamcity-agent-conf:
  dbdatatc:
