version: '3.1'
 
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: accountowner
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
    volumes:
      - dbdata:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: always
    command:  bash -c "/wait-for-it.sh -t 0 db:3306"
  accountownerapp:
    depends_on:
      - db
    image: localhost:50000/codemazeblog/accountowner:build-${BUILD_NUMBER_A}
    command: ["./wait-for-it.sh", "db:3306", "--", "dotnet", "AccountOwnerServer.dll"]
  integration:
    depends_on:
      - accountownerapp
    image: localhost:50000/codemazeblog/accountowner:test
    build:
      context: .
      dockerfile: Dockerfile.Integration
    environment:
      - TEAMCITY_PROJECT_NAME
      
volumes:
    dbdata:
