version: '3.1'
 
services:
  db:
    image: mysql-mine
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: accountowner
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
    volumes:
      - dbdata:/var/lib/mysql
      #- ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: always
  accountownerapp:
    depends_on:
      - db    
    image: "accountownerapp:B${BUILD_NUMBER}"
    build:
      context: .
    command: ["./wait-for-it.sh", "db:3306", "-t", "0", "--", "dotnet", "AccountOwnerServer.dll"]
  integration:
    depends_on:
      - accountownerapp
    image: "accountownerapp:test-B${BUILD_NUMBER}"
    build:
      context: .
      dockerfile: Dockerfile.Integration
    environment:
      - TEAMCITY_PROJECT_NAME
    command: ["./wait-for-it.sh", "db:3306", "-t", "0", "--", "dotnet", "test", "--verbosity=normal"]
      
volumes:
    dbdata:
