FROM microsoft/dotnet:2-sdk
 
WORKDIR /home/app
 
COPY ./*.sln ./
COPY ./*/*.csproj ./
RUN for file in $(ls *.csproj); do mkdir -p ./${file%.*}/ && mv $file ./${file%.*}/; done
 
RUN dotnet restore
 
COPY . .
 
WORKDIR /home/app/Integration/
COPY wait-for-it.sh .

RUN chmod +x ./wait-for-it.sh
 
#ENTRYPOINT ["dotnet", "test", "--verbosity=normal"]
